alg : ppo

sft_model: "GAD-cell/sft_commongen"
reward_model: EleutherAI/pythia-70m
output_dir: "src/models/rl_model"

dataset_name: "allenai/common_gen"

lr: 1.0e-06
k: 2
batch_size: 16
grad_accum: 2
bf16: false

use_lora: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
target_modules: 
  - query_key_value
  - dense
